### ISSUE TITLE
Currently not working

### ISSUE THREAD

**Issue by alexdavliatov** [bpmct/jetbrains-indexer#11]
`Status: Downloaded newer image for bencdr/indexer:idea-2021.3
============================================================
Generating indexes
============================================================
2022-01-25 13:04:16,296 [     63]   WARN - llij.ide.plugins.PluginManager - id redefinition ([row,col,system-id]: [2,3,"product classpath"]) 
Jan 25, 2022 1:04:17 PM java.util.prefs.FileSystemPreferences$1 run
WARNING: Couldn't create user preferences directory. User preferences are unusable.
Jan 25, 2022 1:04:17 PM java.util.prefs.FileSystemPreferences$1 run
WARNING: java.io.IOException: No such file or directory
Jan 25, 2022 1:04:17 PM java.util.prefs.FileSystemPreferences$6 run
WARNING: Prefs file removed in background ?/.java/.userPrefs/prefs.xml
Dump Shared Index command IU-213.5744.223

Failed to parse commandline: /shared-index/output

Usage:
  [idea] dump-shared-index [command] [options]

  The "project" command help:
    Generates shared index for a given project

  Usage:
    [idea] dump-shared-index project [options]

  options:
    --output=<value>              Location of the indexes output directory
                                  it will be updated with generated new indexes

    --project-dir=<value>         Project home directory

    --commit=<value>              [optional] Source Version Control revision

    --compression=<value>         [optional] Compress shared index using: xz, gzip, plain

    --configure-project=<value>   [optional] Call IntelliJ project configurators

    --convert-project=<value>     [optional] Call IntelliJ version converters

    --project-id=<value>          [optional] Project identifier

    --use-xz-compression=<value>  DEPRECATED. Please use 'compression=xz' or 'compression=plain instead
                                  [optional] Shared index can be additionally compressed with xz

2022-01-25 13:04:18,504 [   2271]   WARN - l.NotificationGroupManagerImpl - Notification group CodeWithMe is already registered (group=com.intellij.notification.NotificationGroup@5ec78e22). Plugin descriptor: PluginDescriptor(name=Code With Me, id=com.jetbrains.codeWithMe, descriptorPath=plugin.xml, path=/opt/idea-IU-213.5744.223/plugins/cwm-plugin, version=213.5744.223, package=null, isBundled=true) 
============================================================
Formatting indexes
============================================================
Running the 'cdn-layout-tool' tool 0.8.65
Collected 0 index.json groups
Collected 0 index.json groups
Adding 0 items...
mv: cannot stat '/shared-index/output': No such file or directory
============================================================
Creating intellij.yaml file
============================================================
Wrote the following to intellij.yaml:

sharedIndex:
  project:
    - url: http://localhost:3000/project

Be sure to commit this file to source control so others can use it.
`

**Comment by bpmct** [comment]
Hi! Sorry for the late response, what was the command you ran? Did you mount the project directory with the docker run command?

**Comment by alexdavliatov** [comment]
Hi @bpmct !

Sorry for the late reply.
I execute the same command, as in README.md:
```
docker run -it --rm \
    -v "$(pwd)":/var/project \
    -v "$HOME/indexes-out/IdeaProjects":/shared-index \
    -e INDEXES_CDN_URL=http://localhost:3000/project \
    -u "$(id -u):$(id -g)" \
    bencdr/indexer:idea-2021.3
```
This is the output I get.

```
============================================================
Generating indexes
============================================================
2022-02-01 12:32:21,076 [     43]   WARN - llij.ide.plugins.PluginManager - id redefinition ([row,col,system-id]: [2,3,"product classpath"]) 
Feb 01, 2022 12:32:22 PM java.util.prefs.FileSystemPreferences$1 run
WARNING: Couldn't create user preferences directory. User preferences are unusable.
Feb 01, 2022 12:32:22 PM java.util.prefs.FileSystemPreferences$1 run
WARNING: java.io.IOException: No such file or directory
Feb 01, 2022 12:32:22 PM java.util.prefs.FileSystemPreferences$6 run
WARNING: Prefs file removed in background ?/.java/.userPrefs/prefs.xml
Dump Shared Index command IU-213.5744.223


Failed to parse commandline: /shared-index/output

Usage:
  [idea] dump-shared-index [command] [options]

  The "project" command help:
    Generates shared index for a given project

  Usage:
    [idea] dump-shared-index project [options]

  options:
    --output=<value>              Location of the indexes output directory
                                  it will be updated with generated new indexes

    --project-dir=<value>         Project home directory

    --commit=<value>              [optional] Source Version Control revision

    --compression=<value>         [optional] Compress shared index using: xz, gzip, plain

    --configure-project=<value>   [optional] Call IntelliJ project configurators

    --convert-project=<value>     [optional] Call IntelliJ version converters

    --project-id=<value>          [optional] Project identifier

    --use-xz-compression=<value>  DEPRECATED. Please use 'compression=xz' or 'compression=plain instead
                                  [optional] Shared index can be additionally compressed with xz



2022-02-01 12:32:23,089 [   2056]   WARN - l.NotificationGroupManagerImpl - Notification group CodeWithMe is already registered (group=com.intellij.notification.NotificationGroup@2dfad5cc). Plugin descriptor: PluginDescriptor(name=Code With Me, id=com.jetbrains.codeWithMe, descriptorPath=plugin.xml, path=/opt/idea-IU-213.5744.223/plugins/cwm-plugin, version=213.5744.223, package=null, isBundled=true) 
============================================================
Formatting indexes
============================================================
Running the 'cdn-layout-tool' tool 0.8.65
Collected 0 index.json groups
Collected 0 index.json groups
Adding 0 items...
mv: cannot stat '/shared-index/output': No such file or directory
============================================================
Creating intellij.yaml file
============================================================
note: Your project already has an intellij.yaml file. Be sure to add the following to it:

sharedIndex:
  project:
    - url: http://localhost:3000/project
```

Am I missing smth?

**Comment by alexdavliatov** [comment]
It seems to me, something is missing in the Docker image OR just some silly syntax issue on my Ubuntu

**Comment by bpmct** [comment]
I was able to reproduce this on Ubuntu. It had to do with the `-u` flag mounting the user. Try this

```sh
docker run -it --rm \
    -v "$(pwd)":/var/project \
    -v "$HOME/indexes-out":/shared-index \
    -e INDEXES_CDN_URL=http://localhost:3000/project \
    bencdr/indexer:idea-2021.3
    
# you may need to fix the file permissions for the generated indexes
sudo chown _R $(id -u):$(id -g) $HOME/indexes-out
```

I have updated the README to reflect this and I apologize for the issues!
