### ISSUE TITLE
Files owned by root

### ISSUE THREAD

**Issue by mortenscheel** [bpmct/jetbrains-indexer#8]
I know it probably goes without saying, but maybe you could add a note to the readme mentioning that the files created by the container will be owned by root, including some files in the project .idea folder.

I just ran `sudo find . -user root -exec chown $USER:$USER {} \;` in the project folder to fix it.

**Comment by bpmct** [comment]
This didn't actually happen with mine, perhaps this is a Linux thing? I'm sure I could reproduce it if you share your system.

Is there something we can add to the Dockerfile (or `docker run` args) to fix this? Happy to take a stab once I have a bit more direction

```sh
➜  indexes-out git:(main) ✗ ls -la
total 0
drwxr-xr-x   3 benpotter  staff    96 Dec 22 20:42 .
drwxr-xr-x  32 benpotter  staff  1024 Dec 22 20:31 ..
drwxr-xr-x   5 benpotter  staff   160 Dec 22 20:42 project
```

**Comment by bpmct** [comment]
Ah it looks like this is the reason:

> the files are created by the user that runs within the container. if your containerized command runs as root, then all files will be created as root.
> 
> if you want your files to be created as another user, run the container as this other user. e.g.
>
> `docker run -v "$(pwd)/output":/root/output -u $(whoami) test`

https://unix.stackexchange.com/a/627028

[code-server's Docker command](https://coder.com/docs/code-server/latest/install#docker) specifies the `-u` flag to avoid this. I will add the same to the guide in the README. Let me know if this fixes your issue.
